# ---- Step 1: Build the application ----
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# ---- Step 2: Run the application ----
FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/target/Fitness-Tracker-1.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]